security:
  user:
    name: admin
    password: aghpk
#SHOW SQL
#spring.jpa:
#  show_sql: true
#  format_sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:challenger
    username: sa
    password:
    driver-class-name: org.h2.Driver



