class NotificationTypeEnum {
    static FRIEND_INVITATION = "FRIEND INVITATION";
    static FRIEND_ACCEPTANCE = "FRIEND ACCEPTANCE";
    static CHALLENGE_INVITATION = "CHALLENGE INVITATION";
    static CHALLENGE_ACCEPTANCE = "CHALLENGE ACCEPTANCE";
    static CHALLENGE_REFUSE = "CHALLENGE REFUSAL";
    static CHALLENGE_SUCCESS = "CHALLENGE SUCCESS";
}